definitions:
  dto.AttendanceRequest:
    properties:
      latitude:
        type: string
      longitude:
        type: string
    required:
    - latitude
    - longitude
    type: object
  dto.EmployeeRequest:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      nip:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - date_of_birth
    - email
    - gender
    - name
    - nip
    - password
    - username
    type: object
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.ErrorResp:
    properties:
      errorCode:
        type: integer
      messages: {}
    type: object
  handler.SuccessResp:
    properties:
      data: {}
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /attendances/checkin:
    post:
      consumes:
      - application/json
      description: Record check-in for attendance
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      - description: Attendance Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AttendanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      security:
      - BearerToken: []
      summary: Check-in for attendance
      tags:
      - Attendances
  /attendances/checkout/{id}:
    put:
      consumes:
      - application/json
      description: Record check-out for attendance
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      - description: Attendance ID
        in: path
        name: id
        required: true
        type: integer
      - description: Check Out
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AttendanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      security:
      - BearerToken: []
      summary: Check-out for attendance
      tags:
      - Attendances
  /attendances/history:
    get:
      description: Retrieve a list of all attendance.
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      security:
      - BearerToken: []
      summary: Find Attendance by Employee ID
      tags:
      - Attendances
  /employees:
    delete:
      description: Delete employee by authentication token
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      security:
      - BearerToken: []
      summary: Delete Employee
      tags:
      - Employees
    get:
      description: Retrieve a list of all employees.
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            items:
              $ref: '#/definitions/handler.SuccessResp'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      summary: Retrieve all employees
      tags:
      - Employees
    post:
      consumes:
      - application/json
      description: Create a new employee with the provided data.
      parameters:
      - description: Employee data
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/dto.EmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      summary: Create a new employee
      tags:
      - Employees
    put:
      description: Update employee details by authentication token
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      - description: Employee details to be updated
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.EmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      security:
      - BearerToken: []
      summary: Update Employee
      tags:
      - Employees
  /employees/{nip}:
    get:
      description: Get employee details by NIP
      parameters:
      - description: NIP of the employee
        in: path
        name: nip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/handler.SuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      summary: Find Employee by NIP
      tags:
      - Employees
  /employees/login:
    post:
      consumes:
      - application/json
      description: Login with username and password to get token.
      parameters:
      - description: Login
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResp'
      summary: Login Employee
      tags:
      - Employees
swagger: "2.0"
